const DUNGEON_ACTION_TYPE = {
    NEW_DUNGEON: 'NEW_DUNGEON',
    SET_DUNGEON_SIZE: 'SET_DUNGEON_SIZE',
    MOVE_SELECTED_OBJECT: 'MOVE_SELECTED_OBJECT',
    SET_SELECTED_OBJECT_TEXTURE_PATH: 'SET_SELECTED_OBJECT_TEXTURE_PATH',
    SET_SELECTED_OBJECT_ANGLE: 'SET_SELECTED_OBJECT_ANGLE',
    SET_SELECTED_OBJECT_LABEL: 'SET_SELECTED_OBJECT_LABEL',
    SET_SELECTED_OBJECT_POSITION: 'SET_SELECTED_OBJECT_POSITION',
    SET_SELECTED_OBJECT_SIZE: 'SET_SELECTED_OBJECT_SIZE',
    SET_SELECTED_OBJECT_START: 'SET_SELECTED_OBJECT_START',
    SET_SELECTED_OBJECT_END: 'SET_SELECTED_OBJECT_END',
    ADD_OBJECT: 'ADD_OBJECT',
    DELETE_OBJECTS: 'DELETE_OBJECTS',
    SET_DUNGEON_NAME: 'SET_DUNGEON_NAME'
}

export default DUNGEON_ACTION_TYPE;
