const EDITOR_ACTION_TYPE = {
    PNG_EXPORTED: 'PNG_EXPORTED',
    EXPORT_TO_PNG_CLICKED: 'EXPORT_TO_PNG_CLICKED',
    CLEAR_ONGOING_SPACE_POLYGON: 'CLEAR_ONGOING_SPACE_POLYGON',
    ADD_ONGOING_SPACE_POLYGON: 'ADD_ONGOING_SPACE_POLYGON',
    MOVE_VIEWPORT: 'MOVE_VIEWPORT',
    SET_CURRENT_MOUSE_POSITION: 'SET_CURRENT_MOUSE_POSITION',
    SCROLL_EVENT: 'SCROLL_EVENT',
    MOUSE_DOWN: 'MOUSE_DOWN',
    MOUSE_UP: 'MOUSE_UP',
    SET_SCROLL_MOVES_VIEWPORT: 'SET_SCROLL_MOVES_VIEWPORT',
    SELECT_TOOL: 'SELECT_TOOL',
    SELECT_OBJECT: 'SELECT_OBJECT',
}

export default EDITOR_ACTION_TYPE;
